# Generated by Django 2.1.4 on 2018-12-18 09:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='Add links/name of book')),
                ('is_completed', models.BooleanField(default=False)),
                ('deadline', models.DateField(default=datetime.date.today)),
                ('completed_on', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('is_completed', models.BooleanField(default=False)),
                ('deadline', models.DateField(default=datetime.date.today)),
                ('completed_on', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('total_subjects', models.IntegerField(default=0)),
                ('deadline', models.DateField(default=datetime.date.today)),
                ('completed_on', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('is_completed', models.BooleanField(default=False)),
                ('total_subtopics', models.IntegerField(default=0)),
                ('deadline', models.DateField(default=datetime.date.today)),
                ('completed_on', models.DateField(default=datetime.date.today)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyplanner.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('is_completed', models.BooleanField(default=False)),
                ('deadline', models.DateField(default=datetime.date.today)),
                ('completed_on', models.DateField(default=datetime.date.today)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyplanner.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='path',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyplanner.Subject'),
        ),
        migrations.AddField(
            model_name='method',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studyplanner.Subject'),
        ),
        migrations.AddField(
            model_name='method',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studyplanner.Subtopic'),
        ),
    ]
