# Generated by Django 2.1.4 on 2018-12-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
