# Generated by Django 2.1.4 on 2018-12-18 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0002_plan_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='subject',
        ),
        migrations.AddField(
            model_name='path',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studyplanner.Plan'),
        ),
    ]
