# Generated by Django 2.1.4 on 2018-12-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0003_auto_20181218_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='total_subjects',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='total_subtopics',
        ),
    ]
