# Generated by Django 2.1.4 on 2018-12-19 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0006_auto_20181218_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studyplanner.Path'),
        ),
    ]
