# Generated by Django 2.1.4 on 2018-12-19 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0007_method_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studyplanner.Subject'),
        ),
        migrations.AlterField(
            model_name='method',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studyplanner.Subtopic'),
        ),
    ]
