# Generated by Django 2.1.4 on 2018-12-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0008_auto_20181219_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='completed_methods',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='completed_paths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='completed_subjects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='completed_methods',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='completed_subtopics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='completed_methods',
            field=models.IntegerField(default=0),
        ),
    ]
