# Generated by Django 2.1.4 on 2018-12-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0010_auto_20181219_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='method',
            options={'ordering': ['is_completed']},
        ),
        migrations.AlterModelOptions(
            name='path',
            options={'ordering': ['is_completed']},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['is_completed']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['is_completed']},
        ),
        migrations.AlterModelOptions(
            name='subtopic',
            options={'ordering': ['is_completed']},
        ),
    ]
