# Generated by Django 2.1.4 on 2019-01-03 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0011_auto_20181219_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['is_completed', '-deadline']},
        ),
    ]
